[package]
authors = ["Kornel <kornel@geekhood.net>"]
description = "Unreliable bindings for libpng. They're likely to bring sorrow and regret. Please use a native Rust PNG library instead (e.g. LodePNG 2.0)"
documentation = "http://libpng.org/pub/png/libpng-manual.txt"
homepage = "http://www.libpng.org/pub/png/libpng.html"
license = "Libpng"
links = "png"
name = "libpng-sys"
readme = "README.md"
repository = "https://github.com/pornel/rust-libpng-sys.git"
version = "0.2.1"

[build-dependencies]
cc = "1.0.3"
pkg-config = "0.3.9"
dunce = "0.1.1"

[dependencies]
libc = "0.2.33"
libz-sys = "1.0.18"

[features]
static = []
